products = [
    {
        "id": 1,
        "name": "Wireless Mouse",
        "category": "Electronics",
        "brand": "Logitech",
        "price": 799,
        "discount_price": 699,
        "stock": 120,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
        "description": "Ergonomic wireless mouse with smooth scrolling and long battery life."
    },
    {
        "id": 2,
        "name": "Bluetooth Headphones",
        "category": "Electronics",
        "brand": "Sony",
        "price": 2499,
        "discount_price": 2199,
        "stock": 80,
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e",
        "description": "Over‑ear Bluetooth headphones with noise cancellation."
    },
    {
        "id": 3,
        "name": "Laptop Backpack",
        "category": "Accessories",
        "brand": "American Tourister",
        "price": 1599,
        "discount_price": 1399,
        "stock": 60,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1598033129183-c4f50c736f10",
        "description": "Water‑resistant backpack for laptops up to 15.6 inches."
    },
    {
        "id": 4,
        "name": "Smart Watch",
        "category": "Wearables",
        "brand": "Samsung",
        "price": 3999,
        "discount_price": 3499,
        "stock": 45,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
        "description": "Smartwatch with fitness tracking and notifications."
    },
    {
        "id": 5,
        "name": "Mechanical Keyboard",
        "category": "Electronics",
        "brand": "Redragon",
        "price": 3599,
        "discount_price": 3299,
        "stock": 30,
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
        "description": "RGB mechanical keyboard with tactile switches."
    },
    {
        "id": 6,
        "name": "Running Shoes",
        "category": "Footwear",
        "brand": "Nike",
        "price": 2999,
        "discount_price": 2699,
        "stock": 70,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1528701800489-20be1c1e9d35",
        "description": "Lightweight running shoes with breathable design."
    },
    {
        "id": 7,
        "name": "Coffee Maker",
        "category": "Home Appliances",
        "brand": "Philips",
        "price": 4599,
        "discount_price": 4299,
        "stock": 25,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
        "description": "Automatic coffee maker with fast brewing technology."
    },
    {
        "id": 8,
        "name": "Yoga Mat",
        "category": "Fitness",
        "brand": "Boldfit",
        "price": 899,
        "discount_price": 799,
        "stock": 150,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0",
        "description": "Non‑slip yoga mat ideal for workouts and stretching."
    },
    {
        "id": 9,
        "name": "Bluetooth Speaker",
        "category": "Electronics",
        "brand": "JBL",
        "price": 1999,
        "discount_price": 1799,
        "stock": 90,
        "rating": 4.5,
        "image_url": "https://images.unsplash.com/photo-1585386959984-a4155224a1ad",
        "description": "Portable speaker with powerful bass."
    },
    {
        "id": 10,
        "name": "Office Chair",
        "category": "Furniture",
        "brand": "Green Soul",
        "price": 7999,
        "discount_price": 7399,
        "stock": 18,
        "rating": 4.1,
        "image_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7",
        "description": "Ergonomic office chair with lumbar support."
    },
    {
        "id": 11,
        "name": "USB‑C Charger",
        "category": "Electronics",
        "brand": "Anker",
        "price": 699,
        "discount_price": 599,
        "stock": 200,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1586816001966-79b736744398",
        "description": "Fast‑charging USB‑C wall adapter."
    },
    {
        "id": 12,
        "name": "Smartphone Stand",
        "category": "Accessories",
        "brand": "Portronics",
        "price": 399,
        "discount_price": 349,
        "stock": 250,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1611078489935-0cb964de46d6",
        "description": "Adjustable stand for smartphones."
    },
    {
        "id": 13,
        "name": "Wireless Power Bank",
        "category": "Electronics",
        "brand": "Mi",
        "price": 2499,
        "discount_price": 2199,
        "stock": 65,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1609592425727-3b3e6c3d5f90",
        "description": "High‑capacity wireless power bank."
    },
    {
        "id": 14,
        "name": "Casual Sneakers",
        "category": "Footwear",
        "brand": "Puma",
        "price": 2799,
        "discount_price": 2499,
        "stock": 55,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77",
        "description": "Comfortable sneakers for daily wear."
    },
    {
        "id": 15,
        "name": "Desk Lamp",
        "category": "Home",
        "brand": "Wipro",
        "price": 999,
        "discount_price": 899,
        "stock": 100,
        "rating": 4.1,
        "image_url": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "description": "LED desk lamp with adjustable brightness."
    },
    {
        "id": 16,
        "name": "Wall Clock",
        "category": "Home",
        "brand": "Ajanta",
        "price": 1299,
        "discount_price": 1199,
        "stock": 90,
        "rating": 4.0,
        "image_url": "https://images.unsplash.com/photo-1506368083636-6defb67639b7",
        "description": "Modern wall clock with silent movement."
    },
    {
        "id": 17,
        "name": "Electric Kettle",
        "category": "Home Appliances",
        "brand": "Prestige",
        "price": 1799,
        "discount_price": 1599,
        "stock": 50,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1543536448-d209d2d13a1c",
        "description": "Stainless steel electric kettle."
    },
    {
        "id": 18,
        "name": "Gaming Mouse Pad",
        "category": "Accessories",
        "brand": "Cosmic Byte",
        "price": 499,
        "discount_price": 399,
        "stock": 180,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1615719413546-198b25453f85",
        "description": "Large gaming mouse pad with smooth surface."
    },
    {
        "id": 19,
        "name": "Fitness Band",
        "category": "Wearables",
        "brand": "Xiaomi",
        "price": 1999,
        "discount_price": 1799,
        "stock": 75,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1557935728-e6d1eaabe558",
        "description": "Fitness band with step and sleep tracking."
    },
    {
        "id": 20,
        "name": "Portable SSD",
        "category": "Electronics",
        "brand": "Samsung",
        "price": 6499,
        "discount_price": 5999,
        "stock": 35,
        "rating": 4.6,
        "image_url": "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04",
        "description": "High‑speed portable SSD storage."
    },
    {
        "id": 21,
        "name": "Study Table",
        "category": "Furniture",
        "brand": "IKEA",
        "price": 8999,
        "discount_price": 8299,
        "stock": 20,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1519710888749-93eaa21f6fb5",
        "description": "Minimal wooden study table."
    },
    {
        "id": 22,
        "name": "Wireless Earbuds",
        "category": "Electronics",
        "brand": "Boat",
        "price": 2999,
        "discount_price": 2599,
        "stock": 85,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df",
        "description": "True wireless earbuds with deep bass."
    },
    {
        "id": 23,
        "name": "Kitchen Knife Set",
        "category": "Kitchen",
        "brand": "Pigeon",
        "price": 1499,
        "discount_price": 1299,
        "stock": 60,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1506368083636-6defb67639b7",
        "description": "Sharp stainless steel knife set."
    },
    {
        "id": 24,
        "name": "Water Bottle",
        "category": "Fitness",
        "brand": "Milton",
        "price": 499,
        "discount_price": 449,
        "stock": 200,
        "rating": 4.1,
        "image_url": "https://images.unsplash.com/photo-1523362628745-0c100150b7a1",
        "description": "Leak‑proof stainless steel water bottle."
    },
    {
        "id": 25,
        "name": "Back Cushion",
        "category": "Home",
        "brand": "Wakefit",
        "price": 1299,
        "discount_price": 1099,
        "stock": 90,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1582582429416-2b6e49a14d89",
        "description": "Comfortable memory foam back cushion."
    },
    {
        "id": 26,
        "name": "Table Fan",
        "category": "Home Appliances",
        "brand": "Usha",
        "price": 3199,
        "discount_price": 2899,
        "stock": 40,
        "rating": 4.1,
        "image_url": "https://images.unsplash.com/photo-1593698054589-8c14bb66d3ad",
        "description": "High‑speed table fan with silent operation."
    },
    {
        "id": 27,
        "name": "Camera Tripod",
        "category": "Accessories",
        "brand": "Digitek",
        "price": 1899,
        "discount_price": 1699,
        "stock": 55,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1504215680853-026ed2a45def",
        "description": "Lightweight tripod for cameras and mobiles."
    },
    {
        "id": 28,
        "name": "Electric Iron",
        "category": "Home Appliances",
        "brand": "Bajaj",
        "price": 1599,
        "discount_price": 1399,
        "stock": 65,
        "rating": 4.2,
        "image_url": "https://images.unsplash.com/photo-1581579186988-ec3b1daed23b",
        "description": "Steam iron with non‑stick soleplate."
    },
    {
        "id": 29,
        "name": "Bedside Table",
        "category": "Furniture",
        "brand": "Urban Ladder",
        "price": 4999,
        "discount_price": 4599,
        "stock": 22,
        "rating": 4.3,
        "image_url": "https://images.unsplash.com/photo-1519710164239-da123dc03ef4",
        "description": "Modern bedside table with drawer."
    },
    {
        "id": 30,
        "name": "Laptop Stand",
        "category": "Accessories",
        "brand": "Zebronics",
        "price": 1499,
        "discount_price": 1299,
        "stock": 110,
        "rating": 4.4,
        "image_url": "https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc",
        "description": "Adjustable laptop stand for better posture."
    }
]
