# Generated by Django 6.0.1 on 2026-01-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=90)),
                ("description", models.TextField()),
                (
                    "image_url",
                    models.ImageField(default="default.png", upload_to="product_imgs/"),
                ),
                ("rating", models.FloatField()),
            ],
        ),
    ]
